
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phoenix-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phoenix-prod
  template:
    metadata:
      labels:
        app: phoenix-prod
    spec:
      containers:
      - name: phoenix-prod
        image: phoenix:0.1.0
        imagePullPolicy: Never #This is just because we are using a locally installed image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-prod-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: phoenix-prod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional"
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/phoenix-prod-tls"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "3"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: phoenix-prod-ingress
  namespace: default
spec:
  rules:
  - host: www.phoenixgis.local
    http:
      paths:
      - backend:
          serviceName: phoenix-prod-svc
          servicePort: 80
        path: /
  tls:
  - hosts:
    - www.phoenixgis.local
    secretName: phoenix-prod-tls

